/* Generated with the model by rocketsim/hop/firmware.py. Do not edit; export the model again instead. */
#ifndef POLICY_CONFIG_H
#define POLICY_CONFIG_H

#include "hop_fields.h"
#include "policy_weights.h"

#define POLICY_RESIDUAL 1
#define POLICY_THROTTLE_RANGE 0.4f
#define POLICY_RESIDUAL_GIMBAL 0.0698131701f
static const int POLICY_FIELD_IDS[POLICY_INPUT_SIZE] = {HOP_FIELD_HEIGHT_ERROR, HOP_FIELD_VERTICAL_SPEED_ERROR, HOP_FIELD_REFERENCE_SPEED, HOP_FIELD_HEIGHT, HOP_FIELD_VERTICAL_SPEED, HOP_FIELD_LATERAL_POSITION, HOP_FIELD_LATERAL_SPEED, HOP_FIELD_TILT, HOP_FIELD_TILT_RATE, HOP_FIELD_GIMBAL, HOP_FIELD_THROTTLE, HOP_FIELD_PHASE_ASCENT, HOP_FIELD_PHASE_HOVER, HOP_FIELD_PHASE_DESCENT, HOP_FIELD_PHASE_LANDING};
static const float POLICY_FIELD_SCALES[POLICY_INPUT_SIZE] = {10.0f, 5.0f, 5.0f, 50.0f, 10.0f, 10.0f, 5.0f, 0.5f, 2.0f, 0.17f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};

#endif
