"""Writing a trained network for other runtimes (float32 C arrays for the flight computer, ONNX) and checking both."""

import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np

from rocketsim.env import ACTION_HIGH, ACTION_LOW
from rocketsim.policy import MlpPolicy

WEIGHTS_HEADER = "policy_weights.h"
ONNX_FILE = "policy.onnx"
TOLERANCE = 1e-5
NO_CLIP = 1e30  # stands in for an infinite observation clip in the C header
ONNX_OPSET = 13
ONNX_IR_VERSION = 8
OBSERVATION_SPREAD = 3.0  # random observations are drawn from N(0, spread) in normalised units
FIRMWARE_POLICY = Path(__file__).resolve().parent.parent / "firmware" / "policy"
CHECK_SOURCE = FIRMWARE_POLICY.parent / "tests" / "policy_check.c"


def c_float(value: float) -> str:
    """A float32 C literal; C needs a decimal point or an exponent before the f suffix."""
    if not np.isfinite(value):
        raise ValueError(f"cannot export a non-finite number ({value}); the training run diverged")
    text = f"{float(value):.9g}"
    if "." not in text and "e" not in text:
        text += ".0"
    return text + "f"


def c_array(values: np.ndarray) -> str:
    return "{" + ", ".join(c_float(v) for v in np.asarray(values, dtype=np.float32).ravel()) + "}"


def weights_header(policy: MlpPolicy) -> str:
    """The header with every number the C forward pass needs, as float32 literals."""
    sizes = [policy.weights[0].shape[1]] + [w.shape[0] for w in policy.weights]
    hidden = len(policy.weights) - 1
    lines = [
        "/* Generated by rocketsim/export.py from a trained model. Do not edit; export again instead. */",
        "#ifndef ROCKET_POLICY_WEIGHTS_H",
        "#define ROCKET_POLICY_WEIGHTS_H",
        "",
        "/* Observation fields, in order, each divided by its scale from the training YAML: */",
    ] + [f"/*   {i}: {name} */" for i, name in enumerate(policy.field_names)] + [
        "",
        f"#define POLICY_INPUT_SIZE {sizes[0]}",
        f"#define POLICY_OUTPUT_SIZE {sizes[-1]}",
        f"#define POLICY_HIDDEN_LAYERS {hidden}",
        f"#define POLICY_MAX_WIDTH {max(sizes)}",
        f"#define POLICY_ACTIVATION_TANH {1 if policy.activation == 'tanh' else 0}",
        f"#define POLICY_OBS_CLIP {c_float(policy.obs_clip if np.isfinite(policy.obs_clip) else NO_CLIP)}",
        f"#define POLICY_OUTPUT_LOW {c_float(ACTION_LOW)}",
        f"#define POLICY_OUTPUT_HIGH {c_float(ACTION_HIGH)}",
        "",
        f"static const int POLICY_LAYER_SIZES[{len(sizes)}] = {{{', '.join(str(s) for s in sizes)}}};",
        f"static const float POLICY_OBS_MEAN[POLICY_INPUT_SIZE] = {c_array(policy.obs_mean)};",
        f"static const float POLICY_OBS_STD[POLICY_INPUT_SIZE] = {c_array(policy.obs_std)};",
        "",
    ]
    for i, (weight, bias) in enumerate(zip(policy.weights, policy.biases)):
        lines.append(f"static const float POLICY_W{i}[{weight.size}] = {c_array(weight)};")
        lines.append(f"static const float POLICY_B{i}[{bias.size}] = {c_array(bias)};")
    layers = len(policy.weights)
    lines += [
        "",
        f"static const float *const POLICY_WEIGHTS[{layers}] = {{{', '.join(f'POLICY_W{i}' for i in range(layers))}}};",
        f"static const float *const POLICY_BIASES[{layers}] = {{{', '.join(f'POLICY_B{i}' for i in range(layers))}}};",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def write_onnx(policy: MlpPolicy, path: Path) -> None:
    """The same network as an ONNX graph: normalise, dense layers, clip."""
    import onnx
    from onnx import TensorProto, helper, numpy_helper

    size = policy.weights[0].shape[1]
    inputs = [helper.make_tensor_value_info("observation", TensorProto.FLOAT, [1, size])]
    outputs = [helper.make_tensor_value_info("action", TensorProto.FLOAT, [1, policy.weights[-1].shape[0]])]
    initializers = [
        numpy_helper.from_array(policy.obs_mean.reshape(1, -1), "obs_mean"),
        numpy_helper.from_array(policy.obs_std.reshape(1, -1), "obs_std"),
        numpy_helper.from_array(np.array(-policy.obs_clip, dtype=np.float32), "clip_low"),
        numpy_helper.from_array(np.array(policy.obs_clip, dtype=np.float32), "clip_high"),
        numpy_helper.from_array(np.array(ACTION_LOW, dtype=np.float32), "out_low"),
        numpy_helper.from_array(np.array(ACTION_HIGH, dtype=np.float32), "out_high"),
    ]
    nodes = [
        helper.make_node("Sub", ["observation", "obs_mean"], ["centred"]),
        helper.make_node("Div", ["centred", "obs_std"], ["scaled"]),
        helper.make_node("Clip", ["scaled", "clip_low", "clip_high"], ["x0"]),
    ]
    current = "x0"
    activation = "Tanh" if policy.activation == "tanh" else "Relu"
    for i, (weight, bias) in enumerate(zip(policy.weights, policy.biases)):
        initializers.append(numpy_helper.from_array(weight.T.copy(), f"w{i}"))
        initializers.append(numpy_helper.from_array(bias.copy(), f"b{i}"))
        nodes.append(helper.make_node("Gemm", [current, f"w{i}", f"b{i}"], [f"z{i}"]))
        if i < len(policy.weights) - 1:
            nodes.append(helper.make_node(activation, [f"z{i}"], [f"x{i + 1}"]))
            current = f"x{i + 1}"
        else:
            nodes.append(helper.make_node("Clip", [f"z{i}", "out_low", "out_high"], ["action"]))
    graph = helper.make_graph(nodes, "rocket_landing_policy", inputs, outputs, initializers)
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", ONNX_OPSET)])
    model.ir_version = ONNX_IR_VERSION
    onnx.checker.check_model(model)
    onnx.save(model, str(path))


def random_observations(policy: MlpPolicy, samples: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    size = policy.weights[0].shape[1]
    return (policy.obs_mean + policy.obs_std * rng.normal(size=(samples, size)) * OBSERVATION_SPREAD).astype(np.float32)


def check_c_forward(policy: MlpPolicy, header_dir: Path, samples: int, seed: int) -> float:
    """Compile the C forward pass with the exported header in a clean folder; largest output difference."""
    compiler = shutil.which("gcc") or shutil.which("cc")
    if compiler is None:
        raise RuntimeError("no C compiler (gcc or cc) on PATH to check the export")
    observations = random_observations(policy, samples, seed)
    expected = np.stack([policy.forward(obs) for obs in observations])
    with tempfile.TemporaryDirectory() as folder:
        # The firmware layout is copied so the compiler cannot pick up a stale header next to policy.c.
        build = Path(folder)
        (build / "policy").mkdir()
        (build / "tests").mkdir()
        for source in (FIRMWARE_POLICY / "policy.c", FIRMWARE_POLICY / "policy.h"):
            shutil.copy(source, build / "policy" / source.name)
        shutil.copy(header_dir / WEIGHTS_HEADER, build / "policy" / WEIGHTS_HEADER)
        shutil.copy(CHECK_SOURCE, build / "tests" / CHECK_SOURCE.name)
        binary = build / "policy_check"
        subprocess.run(
            [compiler, "-std=c99", "-O2", "-o", str(binary), str(build / "tests" / CHECK_SOURCE.name),
             str(build / "policy" / "policy.c"), "-lm"],
            check=True, cwd=build,
        )
        text = "\n".join(" ".join(f"{v:.9g}" for v in obs) for obs in observations) + "\n"
        result = subprocess.run([str(binary)], input=text, capture_output=True, text=True, check=True)
    got = np.array([[float(v) for v in line.split()] for line in result.stdout.strip().splitlines()])
    return float(np.max(np.abs(got - expected)))


def check_onnx(policy: MlpPolicy, path: Path, samples: int, seed: int) -> float:
    """Largest difference between the ONNX file run with onnxruntime and the Python policy."""
    import onnxruntime

    session = onnxruntime.InferenceSession(str(path))
    worst = 0.0
    for obs in random_observations(policy, samples, seed):
        got = session.run(None, {"observation": obs[None, :]})[0][0]
        worst = max(worst, float(np.max(np.abs(got - policy.forward(obs)))))
    return worst
